name: "Setup editorconfig-checker"
description: "Downloads the editorconfig-checker binary by version number and adds it to your PATH"
author: "Kasper Hesthaven"
branding:
  icon: play
  color: green
inputs:
  version:
    description: "Version to download, e.g., 2.1.0 or 2.0.4. (default: latest)"
    required: false
  command-name:
    description: "Set editorconfig-checker command name, e.g., 'ec'. (default: editorconfig-checker)"
    required: false
    default: "editorconfig-checker"
runs:
  using: "composite"
  steps:
    - name: Assign latest version if version not provided
      run: |
        if [ -z ${{ inputs.version }} ]; then
            echo "::set-env name=VERSION::$(curl --silent "https://api.github.com/repos/editorconfig-checker/editorconfig-checker/releases/latest" | jq -r .tag_name)"
        else
            echo "::set-env name=VERSION::${{ inputs.version }}"
        fi
      shell: bash

    - name: Assign runner env
      run: |
        if [ ${{ runner.os }} == "Windows" ]; then
            echo "::set-env name=OS::windows"
            echo "::set-env name=EXTENSION::.exe"
            echo "::set-env name=POSIX_PATH::$(echo "/${{ runner.temp }}\ec" | sed -e 's/\\/\//g' -e 's/://' | tr '[:upper:]' '[:lower:]')"
            echo "::set-env name=FINAL_PATH::${{ runner.temp }}\ec"
        else
            echo "::set-env name=OS::$(uname -s | tr '[:upper:]' '[:lower:]')"
            echo "::set-env name=POSIX_PATH::${{ runner.temp }}/ec"
            echo "::set-env name=FINAL_PATH::${{ runner.temp }}/ec"
        fi
      shell: bash

    - name: Download & add to path
      run: |
        echo "Making $POSIX_PATH and changing into it"
        mkdir -p $POSIX_PATH && cd "$_"
        echo "Downloading editorconfig-checker version $VERSION for $OS-amd64 from https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$VERSION/ec-$OS-amd64$EXTENSION.tar.gz"
        curl -L https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$VERSION/ec-$OS-amd64$EXTENSION.tar.gz | tar zx --strip-components 1
        echo "Renaming ec-$OS-amd64$EXTENSION to ${{ inputs.command-name }}$EXTENSION"
        mv ec-$OS-amd64$EXTENSION ${{ inputs.command-name }}$EXTENSION
        echo "Adding $FINAL_PATH to path"
        echo "::add-path::$FINAL_PATH"
      shell: bash
